---
abstract: 'FastCGI server for CGI-like applications multiprocessing'
author:
  - 'Peter V. Vereshagin (peter@vereshagin.org)'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: FCGI-Spawn
no_index:
  directory:
    - t
    - inc
requires:
  Const::Fast: 0
  FCGI: 0
  FCGI::ProcManager: 0
  Test::Most: 0
  Test::Strict: 0
version: v0.16.6
